---
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - main

jobs:
    - job: Windows
      pool:
        vmImage: 'vs2017-win2016'
      timeoutInMinutes: 180
      steps:
      - task: InlinePowershell@1
        pathToSources: src
        inputs:
          Script: 'Write-Output ''Hello world'''

      # Upload agent package zip as build artifact
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact
        inputs:
          pathToPublish: _package
          artifactName: agent
          artifactType: container