pool:
  vmImage: "ubuntu-18.04"

container: ubuntu:18.04

steps:
  - task: shellexec@0
    inputs:
      code: 'su vsts_azpcontainer'
  - task: shellexec@0
    inputs:
      code: |
        ./Tools/CI/Builder/build.sh