pool:
  vmImage: "ubuntu-18.04"

container: ubuntu:18.04

steps:
  - task: shellexec@0
    inputs:
      code: 'cat /etc/os-release'
  - task: shellexec@0
    inputs:
      code: |
        #!/bin/bash
        echo Hello World --- init
        ls -lsa 

