---
trigger:
  - master

jobs:
  - job: macOS1014
    pool:
      vmImage: "macOS-10.14"
    timeoutInMinutes: 180
    steps:
    - task: shellexec@0
      inputs:
        code: |
          echo building $(Build.BuildNumber)
    - task: shellexec@0
      inputs:
        code: |
          pwd
          ls -lsa
          curl --version
          curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
          sudo installer -pkg AWSCLIV2.pkg -target /
          aws --version

          


