pool:
  vmImage: "ubuntu-18.04"

container: ubuntu:18.04

steps:
  - task: shellexec@0
    inputs:
      code: 'cat /etc/os-release'
  - task: shellexec@0
    inputs:
      code: |
        #!/bin/bash
        echo Hello World --- init
        ls -lsa 
        apt update && sudo apt upgrade -y
        apt install curl -y
        curl --version
        curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip -o awscliv2.zip
        unzip awscliv2.zip
        ./aws/install
        aws --version