pool:
  vmImage: "macos-latest"

container: macos-latest

steps:
  - task: shellexec@0
    inputs:
      code: 'brew install curl'
  - task: shellexec@0
    inputs:
      code: |
        curl --version