---
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - main

jobs:
    - job: Windows
      pool:
        vmImage: 'vs2017-win2016'
      timeoutInMinutes: 180
      steps:
      - task: InlinePowershell@1
        displayName: Calling Powershell
        inputs:
          Script: 'Write-Output ''Hello world'''

      - task: ChocolateyToolInstaller@0
        displayName: Install Chocolatey
        inputs:
          force: true