- task: shellexec@0
  inputs:
    code: 'pwd'
- task: WaitForBuildToFinish@2
  inputs:
    definitionIsInCurrentTeamProject: true
    ignoreSslCertificateErrors: false
    waitForQueuedBuildsToFinishRefreshTime: '60'
    failTaskIfBuildsNotSuccessful: true
    cancelBuildsIfAnyFails: true
    treatPartiallySucceededBuildAsSuccessful: false
    downloadBuildArtifacts: true
    clearVariable: true
    authenticationMethod: 'Personal Access Token'