---
trigger:
  - master

jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        # <-- SNIP BEGIN -->
        py27:
          python.version: '2.7'
          tox.env: py27
        py37:
          python.version: '3.7'
          tox.env: py37
        docs:
          python.version: '3.7'
          tox.env: docs
        # <-- SNIP END -->

