pool:
  vmImage: "Ubuntu-16.04"

container: Ubuntu-16.04

steps:
  - task: shellexec@0
    inputs:
      code: 'sudo apt-get install -y default-jre'
  - task: shellexec@0
    inputs:
      code: |
        ./Tools/CI/Builder/build.sh