pool:
  vmImage: "ubuntu-18.04"

container: ubuntu:18.04

steps:

# maven-package-owasp-scan.yml@templates
stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Pacakge
        steps:
          - bash: pwd
            displayName: mvn package
