# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Copied article from
# https://github.com/WOA-Project/Lumia950XLPkg/blob/master/azure-pipelines.yml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: AWS Credentials

steps:
  # Write the installed version to the command line
  - task: CmdLine@2
    inputs:
      script: sudo apt update
    displayName: 'Update APT sources'

