---
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - main

jobs:
    - job: Windows
      pool:
        vmImage: 'vs2017-win2016'
      timeoutInMinutes: 180
      steps:
      - task: InlinePowershell@1
        displayName: Calling Powershell
        inputs:
          Script: 'Write-Output ''Hello world'''
      - task: InlinePowershell@1
        inputs:
          Script: |
            Set-ExecutionPolicy Bypass -Scope Process -Force;
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
            iex ((New-Object System.Net.WebClient).DownloadString(''https://chocolatey.org/install.ps1''))
    