# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Copied article from
# https://github.com/WOA-Project/Lumia950XLPkg/blob/master/azure-pipelines.yml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: AWS Credentials

steps:

  - script: sudo apt update
    displayName: 'Update APT sources'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: ./Tools/CI/Bootstrapper/init.sh
    displayName: 'Prepare pre-build environment, init phase'

  - script: ./Tools/CI/Builder/Build.sh
    displayName: 'build phase'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - script: |
      sudo pip3 install --upgrade pip
      pip3 install awscli --upgrade --user
      export PATH="/home/vsts/.local/bin:$PATH"
      aws --version
      echo What
      echo $AWS_ACCESS_KEY_ID
    displayName: 'Install AWS CLI'

