---
trigger:
  - master

jobs:
  - job: macOS1014
    pool:
      vmImage: "macOS-10.14"
    steps:
      - script: echo hello from macOS Mojave
  - job: macOS1013
    pool:
      vmImage: "macOS-10.13"
    steps:
      - script: echo hello from macOS High Sierra
  - job: macOSlatest
    pool:
      vmImage: "macOS-latest"
    steps:
      - script: echo hello from the latest version of macOS available
